Next value: 1
Exception:
Finally
